(()=>{
'use strict';
const VERSION='5.0.0';
const KEY='p85v5_state';
const LEGACY_KEYS=['p85pro2_state','p85proclean_state','p85_state'];
const $=s=>document.querySelector(s); const app=document.getElementById('app');
const iso=d=>{const x=new Date(d.getFullYear(),d.getMonth(),d.getDate());return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
const today=()=>iso(new Date()); const parseDate=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)};
const addDays=(s,n)=>{const d=parseDate(s);d.setDate(d.getDate()+n);return iso(d)};
const monday=(s=today())=>{const d=parseDate(s);const n=(d.getDay()+6)%7;d.setDate(d.getDate()-n);return iso(d)};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const safeParse=(s,f=null)=>{try{return JSON.parse(s)}catch{return f}};
const uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
const escapeHtml=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

const EXERCISES=[
{id:'leg_press',name:'Prensa de piernas',pattern:'Piernas',eq:'Prensa',icon:'🦵',core:false},
{id:'hack',name:'Hack squat en máquina',pattern:'Piernas',eq:'Hack squat',icon:'🦵',core:false},
{id:'leg_ext',name:'Extensión de cuádriceps',pattern:'Piernas',eq:'Extensión',icon:'🦵',core:false},
{id:'leg_curl',name:'Curl femoral',pattern:'Piernas',eq:'Curl femoral',icon:'🦵',core:false},
{id:'abductor',name:'Abducción en máquina',pattern:'Cadera',eq:'Abducción',icon:'↔️',core:false},
{id:'adductor',name:'Aducción en máquina',pattern:'Cadera',eq:'Aducción',icon:'↔️',core:false},
{id:'calf',name:'Gemelo en máquina',pattern:'Piernas',eq:'Gemelo',icon:'🦶',core:false},
{id:'lat_pull',name:'Jalón al pecho',pattern:'Espalda',eq:'Polea',icon:'🔽',core:false},
{id:'neutral_pull',name:'Jalón agarre neutro',pattern:'Espalda',eq:'Polea',icon:'🔽',core:false},
{id:'row',name:'Remo sentado',pattern:'Espalda',eq:'Remo',icon:'🚣',core:false},
{id:'chest_row',name:'Remo con apoyo de pecho',pattern:'Espalda',eq:'Remo pecho',icon:'🚣',core:false},
{id:'pullover',name:'Pullover en máquina/polea',pattern:'Espalda',eq:'Polea',icon:'⬇️',core:false},
{id:'chest_press',name:'Press de pecho en máquina',pattern:'Pecho',eq:'Press pecho',icon:'💪',core:false},
{id:'incline_press',name:'Press inclinado en máquina',pattern:'Pecho',eq:'Press inclinado',icon:'💪',core:false},
{id:'pecdeck',name:'Peck deck',pattern:'Pecho',eq:'Peck deck',icon:'🪽',core:false},
{id:'shoulder_press',name:'Press de hombro en máquina',pattern:'Hombros',eq:'Press hombro',icon:'⬆️',core:false},
{id:'lateral',name:'Elevación lateral',pattern:'Hombros',eq:'Mancuernas/Polea',icon:'↗️',core:false},
{id:'rear_delt',name:'Deltoide posterior',pattern:'Hombros',eq:'Peck deck inverso',icon:'🪽',core:false},
{id:'facepull',name:'Face pull',pattern:'Espalda',eq:'Polea',icon:'🎯',core:false},
{id:'biceps',name:'Curl de bíceps en máquina',pattern:'Brazos',eq:'Bíceps',icon:'💪',core:false},
{id:'hammer',name:'Curl martillo',pattern:'Brazos',eq:'Mancuernas',icon:'🔨',core:false},
{id:'triceps',name:'Extensión de tríceps en polea',pattern:'Brazos',eq:'Polea',icon:'💪',core:false},
{id:'triceps_machine',name:'Tríceps en máquina',pattern:'Brazos',eq:'Tríceps',icon:'💪',core:false},
{id:'crunch',name:'Crunch en máquina',pattern:'Core',eq:'Core',icon:'◎',core:true},
{id:'rotation',name:'Rotación de torso en máquina',pattern:'Core',eq:'Core',icon:'↻',core:true},
{id:'back_ext',name:'Extensión lumbar suave en máquina',pattern:'Core',eq:'Core',icon:'◉',core:true},
{id:'neck',name:'Movilidad cervical suave',pattern:'Movilidad',eq:'Sin carga',icon:'🧘',core:false}
];
const MEALS=[
{id:'salmon_rice',name:'Salmón con arroz y verduras',kind:'lunch',groups:['Pescado','Cereal','Verdura'],ingredients:['salmón','arroz','verduras']},
{id:'cod_pepper',name:'Bacalao al horno con pimientos',kind:'lunch',groups:['Pescado','Verdura'],ingredients:['bacalao','pimientos','cebolla']},
{id:'prawn_rice',name:'Arroz con langostinos y verduras',kind:'lunch',groups:['Marisco','Cereal','Verdura'],ingredients:['arroz','langostinos','verduras']},
{id:'chicken_pasta',name:'Pasta mediterránea con pollo',kind:'lunch',groups:['Ave','Cereal','Verdura'],ingredients:['pasta','pollo','tomate','espinacas']},
{id:'turkey_rice',name:'Pavo al horno con arroz y ensalada',kind:'lunch',groups:['Ave','Cereal','Verdura'],ingredients:['pavo','arroz','ensalada']},
{id:'pork_veg',name:'Lomo magro con verduras salteadas',kind:'lunch',groups:['Carne','Verdura'],ingredients:['lomo','verduras']},
{id:'beef_salad',name:'Ternera a la plancha con ensalada completa',kind:'lunch',groups:['Carne','Verdura'],ingredients:['ternera','ensalada']},
{id:'chickpea_spinach',name:'Garbanzos con espinacas y huevo',kind:'lunch',groups:['Legumbre','Verdura','Huevo'],ingredients:['garbanzos','espinacas','huevo']},
{id:'lentil_veg',name:'Lentejas con verduras',kind:'lunch',groups:['Legumbre','Verdura'],ingredients:['lentejas','verduras']},
{id:'bean_tuna',name:'Ensalada de judías, atún y tomate',kind:'lunch',groups:['Legumbre','Pescado','Verdura'],ingredients:['judías','atún','tomate']},
{id:'omelette_pepper',name:'Tortilla con pimientos asados y tomate',kind:'dinner',groups:['Huevo','Verdura'],ingredients:['huevos','pimientos','tomate']},
{id:'wrap_chicken',name:'Wrap integral de pollo, guacamole y tomate',kind:'dinner',groups:['Ave','Cereal','Verdura'],ingredients:['tortilla integral','pollo','aguacate','tomate']},
{id:'tuna_toast',name:'Tosta integral con atún, tomate y aguacate',kind:'dinner',groups:['Pescado','Cereal','Verdura'],ingredients:['pan integral','atún','tomate','aguacate']},
{id:'prawn_salad',name:'Ensalada templada de langostinos',kind:'dinner',groups:['Marisco','Verdura'],ingredients:['langostinos','ensalada','tomate']},
{id:'egg_tuna',name:'Huevo cocido con atún y ensalada',kind:'dinner',groups:['Huevo','Pescado','Verdura'],ingredients:['huevo','atún','ensalada']},
{id:'turkey_toast',name:'Tosta integral de pavo, tomate y queso fresco',kind:'dinner',groups:['Ave','Cereal','Lácteo','Verdura'],ingredients:['pan integral','pavo','tomate','queso fresco']},
{id:'gulas_egg',name:'Gulas salteadas con huevo y verduras',kind:'dinner',groups:['Pescado','Huevo','Verdura'],ingredients:['gulas','huevo','verduras']},
{id:'veg_omelette',name:'Revuelto de huevo con verduras y pan integral',kind:'dinner',groups:['Huevo','Verdura','Cereal'],ingredients:['huevo','verduras','pan integral']}
];

function defaultState(){
 return {version:VERSION,createdAt:new Date().toISOString(),route:'home',sub:{training:'today',nutrition:'today',evolution:'summary'},
  profile:{name:'',gym:'Mi gimnasio',theme:'light'},
  gym:{available:Object.fromEntries(EXERCISES.map(x=>[x.eq,true]))},
  checkins:[],pain:[],sessions:[],measurements:[],mealHistory:[],mealRatings:{},customMeals:[],weeklyPlans:{},shopping:[],pantry:[],
  prefs:{dislikedMeals:[],favoriteMeals:[],avoidExercises:[]},meta:{migrated:false,legacySnapshot:null}};
}
function save(){state.version=VERSION;localStorage.setItem(KEY,JSON.stringify(state))}
function load(){let s=safeParse(localStorage.getItem(KEY));if(!s)s=defaultState();return normalize(s)}
function normalize(s){const d=defaultState(); const out={...d,...s};out.profile={...d.profile,...(s.profile||{})};out.gym={...d.gym,...(s.gym||{})};out.sub={...d.sub,...(s.sub||{})};out.prefs={...d.prefs,...(s.prefs||{})};out.meta={...d.meta,...(s.meta||{})};['checkins','pain','sessions','measurements','mealHistory','customMeals','shopping','pantry'].forEach(k=>{if(!Array.isArray(out[k]))out[k]=[]});if(!out.weeklyPlans||typeof out.weeklyPlans!=='object')out.weeklyPlans={};if(!out.mealRatings||typeof out.mealRatings!=='object')out.mealRatings={};return out}
let state=load(); let modal=null;
function tryLegacy(){if(state.meta.migrated)return;for(const k of LEGACY_KEYS){const raw=localStorage.getItem(k);if(!raw)continue;const old=safeParse(raw);if(!old)continue;state.meta.legacySnapshot={key:k,raw,at:new Date().toISOString()};
  // Read-only heuristic import; never deletes legacy data.
  const candidates=[old,old.state,old.data].filter(Boolean);
  for(const c of candidates){if(Array.isArray(c.measurements)&&!state.measurements.length)state.measurements=c.measurements;if(Array.isArray(c.sessions)&&!state.sessions.length)state.sessions=c.sessions;if(Array.isArray(c.trainingSessions)&&!state.sessions.length)state.sessions=c.trainingSessions;if(Array.isArray(c.pantry)&&!state.pantry.length)state.pantry=c.pantry;if(Array.isArray(c.shopping)&&!state.shopping.length)state.shopping=c.shopping;if(c.weeklyPlans&&typeof c.weeklyPlans==='object')state.weeklyPlans={...c.weeklyPlans,...state.weeklyPlans};}
  break;
 } state.meta.migrated=true;save();}
tryLegacy();

function lastCheckin(){return [...state.checkins].sort((a,b)=>b.date.localeCompare(a.date))[0]||null}
function recoveryStatus(){const c=lastCheckin();if(!c||c.date!==today())return {level:'unknown',label:'Sin check-in',cls:''};if(c.pain>=7||c.energy<=2||c.fatigue>=8)return {level:'red',label:'Recuperación',cls:'bad'};if(c.pain>=4||c.energy<=4||c.fatigue>=6||c.bloating>=6)return {level:'yellow',label:'Suave',cls:'warn'};return {level:'green',label:'Normal',cls:'good'}}
function currentWeek(){return monday(today())}
function sessionHistoryIds(){
 const done=state.sessions.flatMap(s=>(s.exercises||[]).map(e=>e.id));
 const planned=Object.keys(state.weeklyPlans).sort().slice(-3).flatMap(k=>(state.weeklyPlans[k]?.workouts||[]).flatMap(w=>(w.exercises||[]).map(e=>e.id)));
 return [...done,...planned].slice(-120);
}
function availableExercise(x){return state.gym.available[x.eq]!==false&&!state.prefs.avoidExercises.includes(x.id)}
function weightedPick(pool,used,recent){const scored=pool.map(x=>{const rc=recent.filter(id=>id===x.id).length;const uc=used.includes(x.id)?4:0;return {x,score:Math.random()*2-rc*1.8-uc*4}}).sort((a,b)=>b.score-a.score);return scored[0]?.x}
function generateWorkout(dayIndex=0,force=false,weekKey=currentWeek()){const key=weekKey;const plan=state.weeklyPlans[key]||{};if(plan.workouts&&!force)return plan.workouts[dayIndex];const recent=sessionHistoryIds();const days=[];for(let d=0;d<5;d++){const used=[];const patterns=['Piernas','Espalda','Pecho','Hombros','Brazos','Core'];const exs=[];for(const p of patterns){let pool=EXERCISES.filter(x=>x.pattern===p&&availableExercise(x));if(!pool.length)continue;let pick=weightedPick(pool,used,recent);if(pick){used.push(pick.id);exs.push({...pick,sets:p==='Core'?2:3,reps:p==='Core'?'cómodo':'8–12'});}}
  // Add one rotating accessory, avoiding excessive volume.
  const accessory=weightedPick(EXERCISES.filter(x=>['Cadera','Movilidad'].includes(x.pattern)&&availableExercise(x)),used,recent);if(accessory)exs.push({...accessory,sets:2,reps:'cómodo'});
  days.push({name:['Base','Tirón','Equilibrio','Empuje','Completa'][d],exercises:exs,cardio:d===2?'20–25 min suave':'15–25 min cómodo'});
 }
 state.weeklyPlans[key]={...(state.weeklyPlans[key]||{}),workouts:days,generatedAt:new Date().toISOString()};save();return days[dayIndex]}
function mealRecentIds(){
 const hist=state.mealHistory.slice(-28).map(x=>x.mealId);
 const weeks=Object.keys(state.weeklyPlans).sort().slice(-4);
 const planned=weeks.flatMap(k=>(state.weeklyPlans[k]?.meals||[]).flatMap(x=>[x.lunch,x.dinner])).filter(Boolean);
 return [...hist,...planned];
}
function chooseMeal(kind,used){const recent=mealRecentIds();const custom=state.customMeals.filter(x=>x.kind===kind);const pool=[...MEALS.filter(x=>x.kind===kind),...custom].filter(x=>!state.prefs.dislikedMeals.includes(x.id));const ranked=pool.map(m=>({m,score:Math.random()*3-(recent.filter(id=>id===m.id).length*3)-(used.includes(m.id)?8:0)+(state.prefs.favoriteMeals.includes(m.id)?1:0)})).sort((a,b)=>b.score-a.score);return ranked[0]?.m}
function generateMeals(force=false,weekKey=currentWeek()){const key=weekKey;const plan=state.weeklyPlans[key]||{};if(plan.meals&&!force)return plan.meals;const used=[];const meals=[];for(let i=0;i<7;i++){const lunch=chooseMeal('lunch',used);if(lunch)used.push(lunch.id);const dinner=chooseMeal('dinner',used);if(dinner)used.push(dinner.id);meals.push({date:addDays(key,i),lunch:lunch?.id,dinner:dinner?.id});}state.weeklyPlans[key]={...plan,meals,generatedAt:new Date().toISOString()};save();return meals}
function allMeals(){return [...MEALS,...state.customMeals]}
function mealById(id){return allMeals().find(x=>x.id===id)}
function todayMealPlan(){return generateMeals(false,currentWeek()).find(x=>x.date===today())||generateMeals(false,currentWeek())[0]}
function trainingDayIndex(){const d=(parseDate(today()).getDay()+6)%7;return clamp(d,0,4)}
function planWorkoutToday(){return generateWorkout(trainingDayIndex(),false,currentWeek())}

function nav(){return `<nav class="nav">${[['home','⌂','Hoy'],['training','🏋️','Entreno'],['nutrition','🍽️','Comidas'],['evolution','📈','Evolución'],['more','•••','Más']].map(([r,i,l])=>`<button data-route="${r}" class="${state.route===r?'active':''}"><span class="ico">${i}</span>${l}</button>`).join('')}</nav>`}
function shell(content){return `<div class="topbar"><div class="brand"><div class="logo">85</div><div><div class="title">Proyecto85</div><div class="subtitle">v${VERSION} · adaptable, variado y simple</div></div></div><span class="pill ${recoveryStatus().cls}">${recoveryStatus().label}</span></div>${content}${nav()}${modal||''}`}
function home(){const st=recoveryStatus();const w=planWorkoutToday();const mp=todayMealPlan();const lunch=mealById(mp.lunch),dinner=mealById(mp.dinner);const completed=state.sessions.filter(s=>s.week===currentWeek()).length;return shell(`
 <section class="card hero"><span class="pill ${st.cls}">${st.level==='unknown'?'¿Cómo estás hoy?':`Estado: ${st.label}`}</span><h1>${st.level==='yellow'||st.level==='red'?'Hoy manda la recuperación':'Tu día, sin piloto automático'}</h1><p>${st.level==='yellow'||st.level==='red'?'La app reduce exigencia y evita progresiones automáticas cuando reportas cansancio o molestias.':'Cada semana combina continuidad y variación para que puedas progresar sin sentir que repites siempre lo mismo.'}</p><div class="btnrow" style="margin-top:14px"><button class="btn ${st.level==='unknown'?'recovery':'secondary'}" data-action="checkin">Check-in de hoy</button><button class="btn secondary" data-action="surprise">Sorpréndeme esta semana</button></div></section>
 <div class="grid2"><section class="card"><span class="pill">ENTRENAMIENTO</span><h2>${escapeHtml(w.name)}</h2><p class="muted">${w.exercises.length} ejercicios · cardio ${w.cardio}</p><button class="btn primary block" data-route="training">Ver sesión</button></section>
 <section class="card"><span class="pill">NUTRICIÓN</span><h2>${escapeHtml(lunch?.name||'Plan del día')}</h2><p class="muted">Cena: ${escapeHtml(dinner?.name||'por definir')}</p><button class="btn food block" data-route="nutrition">Ver día</button></section></div>
 <section class="card"><div class="section-title"><h2>Esta semana</h2><span class="pill">${completed}/5 sesiones</span></div><div class="progress"><span style="width:${Math.min(100,completed/5*100)}%"></span></div><div class="week-strip" style="margin-top:12px">${['L','M','X','J','V','S','D'].map((x,i)=>`<div class="daydot ${addDays(currentWeek(),i)===today()?'active':''}">${x}</div>`).join('')}</div></section>
 <section class="card"><span class="pill">ENTRENADOR85</span><h3>¿Qué debería tener en cuenta hoy?</h3><p class="muted">${st.level==='red'?'Has marcado señales de recuperación. Evita forzar ejercicios que provoquen dolor y prioriza sensaciones cómodas.':st.level==='yellow'?'Hoy conviene una sesión más suave y sin perseguir progresión.':'Usa el botón Molestia/dolor en cualquier ejercicio si algo no se siente bien.'}</p><button class="linkbtn" data-action="coach">Preguntar a Entrenador85 →</button></section>`)}

function training(){const tab=state.sub.training;const tabs=['today','week','progress','gym'];return shell(`<div class="tabs">${tabs.map(t=>`<button class="tab ${tab===t?'active':''}" data-trtab="${t}">${({today:'Hoy',week:'5 días',progress:'Progreso',gym:'Mi gimnasio'})[t]}</button>`).join('')}</div>${tab==='today'?trainingToday():tab==='week'?trainingWeek():tab==='progress'?trainingProgress():gymView()}`)}
function trainingToday(){let w=planWorkoutToday();const st=recoveryStatus();if(st.level==='yellow')w={...w,exercises:w.exercises.slice(0,5).map(e=>({...e,sets:Math.min(2,e.sets)})),cardio:'10–20 min cómodo'};if(st.level==='red')w={...w,exercises:w.exercises.filter(e=>e.pattern==='Core'||e.pattern==='Movilidad'||e.pattern==='Espalda'||e.pattern==='Pecho').slice(0,4).map(e=>({...e,sets:1})),cardio:'opcional, muy suave'};return `<section class="card"><div class="section-title"><h2>${escapeHtml(w.name)}</h2><span class="pill ${st.cls}">${st.label}</span></div><p class="muted">${st.level==='yellow'||st.level==='red'?'Modo recuperación: mantén intensidad cómoda y no busques aumentar carga.':'Conservamos parte de la rutina y rotamos accesorios para mantener variedad.'}</p>${w.exercises.map((e,i)=>exerciseRow(e,i)).join('')}<div class="divider"></div><div class="statline"><b>Cardio</b><span class="pill">${w.cardio}</span></div><div class="btnrow" style="margin-top:14px"><button class="btn primary" data-action="startSession">Empezar sesión</button><button class="btn secondary" data-action="regenWorkout">Nueva combinación</button></div></section>`}
function exerciseRow(e,i){const last=[...state.sessions].reverse().flatMap(s=>s.exercises||[]).find(x=>x.id===e.id);return `<div class="exercise"><div class="exicon">${e.icon}</div><div><b>${escapeHtml(e.name)}</b><div class="tags"><span class="tag">${e.pattern}</span><span class="tag">${e.eq}</span><span class="tag">${e.sets} series</span>${last?`<span class="tag">Anterior: ${escapeHtml(last.summary||'registrado')}</span>`:''}</div></div><button class="linkbtn" data-ex="${e.id}" data-index="${i}">Abrir</button></div>`}
function trainingWeek(){const p=state.weeklyPlans[currentWeek()]||{};const ws=p.workouts||[0,1,2,3,4].map(i=>generateWorkout(i));return `<section class="card"><h2>Plan de 5 días</h2><p class="muted">La estructura se mantiene reconocible, pero los ejercicios rotan según historial, equipamiento y preferencias.</p>${ws.map((w,i)=>`<div class="meal"><div class="mealhead"><div><h4>${['Lunes','Martes','Miércoles','Jueves','Viernes'][i]} · ${escapeHtml(w.name)}</h4><p>${w.exercises.map(x=>x.name).join(' · ')}</p></div><span class="pill">${w.exercises.length}</span></div></div>`).join('')}<button class="btn secondary block" data-action="regenWorkout">Regenerar semana de entrenamiento</button></section>`}
function trainingProgress(){const week=state.sessions.filter(s=>s.week===currentWeek());const recent=state.sessions.slice(-10);return `<section class="card"><h2>Tu progreso, contra tu propio historial</h2><div class="grid2"><div class="metric"><strong>${week.length}</strong><span>sesiones esta semana</span></div><div class="metric"><strong>${state.sessions.length}</strong><span>sesiones registradas</span></div></div></section><section class="card"><h3>Sesiones recientes</h3>${recent.length?recent.reverse().map(s=>`<div class="statline"><span>${escapeHtml(s.date)} · ${escapeHtml(s.name||'Sesión')}</span><span class="pill">${s.exercises?.length||0} ej.</span></div>`).join(''):'<div class="empty">Aún no hay sesiones registradas.</div>'}</section>`}
function gymView(){return `<section class="card"><h2>Mi gimnasio</h2><p class="muted">Activa solo el equipamiento que realmente tienes disponible. El generador no propondrá máquinas desactivadas.</p><label>Nombre del gimnasio</label><input class="input" id="gymName" value="${escapeHtml(state.profile.gym)}"><div class="divider"></div>${[...new Set(EXERCISES.map(x=>x.eq))].map(eq=>`<div class="statline"><span>${escapeHtml(eq)}</span><input type="checkbox" data-gym="${escapeHtml(eq)}" ${state.gym.available[eq]!==false?'checked':''}></div>`).join('')}<button class="btn primary block" style="margin-top:14px" data-action="saveGym">Guardar Mi gimnasio</button>${state.prefs.avoidExercises.length?`<div class="divider"></div><h3>Ejercicios pausados por molestias</h3>${state.prefs.avoidExercises.map(id=>{const e=EXERCISES.find(x=>x.id===id);return e?`<div class="statline"><span>${escapeHtml(e.name)}</span><button class="linkbtn" data-restore-ex="${id}">Volver a permitir</button></div>`:''}).join('')}`:''}</section>`}

function nutrition(){const tab=state.sub.nutrition;const tabs=['today','week','organize','shopping'];return shell(`<div class="tabs">${tabs.map(t=>`<button class="tab ${tab===t?'active':''}" data-nutab="${t}">${({today:'Hoy',week:'Semana',organize:'Próxima semana',shopping:'Compra'})[t]}</button>`).join('')}</div>${tab==='today'?nutritionToday():tab==='week'?nutritionWeek():tab==='organize'?nutritionOrganize():shoppingView()}`)}
function mealCard(label,m){if(!m)return '';return `<div class="meal"><div class="mealhead"><div><h4>${label} · ${escapeHtml(m.name)}</h4><p>${(m.groups||[]).join(' · ')}</p></div><span class="pill">${state.prefs.favoriteMeals.includes(m.id)?'★ Favorito':'Variado'}</span></div><div class="btnrow"><button class="btn secondary" data-change-meal="${m.id}">Cambiar</button><button class="btn secondary" data-fav-meal="${m.id}">${state.prefs.favoriteMeals.includes(m.id)?'Quitar favorito':'Favorito'}</button><button class="btn secondary" data-dislike-meal="${m.id}">No repetir</button></div></div>`}
function nutritionToday(){const p=todayMealPlan();return `<section class="card"><h2>Comidas de hoy</h2><p class="muted">Plan regular, variado y práctico. Sin compensaciones ni restricciones por una semana difícil.</p>${mealCard('Comida',mealById(p.lunch))}${mealCard('Cena',mealById(p.dinner))}</section><section class="card"><span class="pill">APRENDE CONMIGO</span><h3>La variedad también es una herramienta</h3><p class="muted">El plan intenta alternar fuentes de proteína, verduras, legumbres y cereales para que la semana no se convierta en una repetición automática.</p></section>`}
function nutritionWeek(){const ms=generateMeals();return `<section class="card"><div class="section-title"><h2>${currentWeek()} → ${addDays(currentWeek(),6)}</h2><button class="linkbtn" data-action="regenMeals">Nueva propuesta</button></div>${ms.map((d,i)=>`<div class="meal"><h4>${['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'][i]}</h4><p><b>Comida:</b> ${escapeHtml(mealById(d.lunch)?.name||'')}</p><p><b>Cena:</b> ${escapeHtml(mealById(d.dinner)?.name||'')}</p></div>`).join('')}</section>`}
function nutritionOrganize(){const next=addDays(currentWeek(),7);const ms=generateMeals(false,next);const ids=ms.flatMap(x=>[x.lunch,x.dinner]);const unique=new Set(ids).size;const groups={};ids.map(mealById).filter(Boolean).forEach(m=>new Set(m.groups||[]).forEach(g=>groups[g]=(groups[g]||0)+1));const wp=state.weeklyPlans[next]||{};const workouts=wp.workouts||[0,1,2,3,4].map(i=>generateWorkout(i,false,next));return `<section class="card"><span class="pill">PLANIFICAR</span><h2>Próxima semana · ${next} → ${addDays(next,6)}</h2><p class="muted">Proyecto85 revisa lo usado recientemente para evitar una semana clonada.</p><div class="grid2"><div class="metric"><strong>${unique}/14</strong><span>platos distintos</span></div><div class="metric"><strong>${new Set(workouts.flatMap(w=>w.exercises.map(e=>e.id))).size}</strong><span>ejercicios diferentes</span></div></div><div class="divider"></div><h3>Variedad alimentaria</h3><div class="statlist">${Object.entries(groups).map(([g,n])=>`<div class="statline"><span>${g}</span><span class="pill">${n} platos</span></div>`).join('')}</div><p class="small muted">Un plato puede contar en varios grupos. Es una descripción de variedad, no una puntuación corporal.</p><div class="btnrow" style="margin-top:14px"><button class="btn food" data-action="regenNextWeek">Sorpréndeme la próxima semana</button><button class="btn secondary" data-action="makeShoppingNext">Crear compra</button></div></section><section class="card"><h3>Vista previa de entrenamientos</h3>${workouts.map((w,i)=>`<div class="statline"><span>${['L','M','X','J','V'][i]} · ${escapeHtml(w.name)}</span><span class="pill">${w.exercises.length} ej.</span></div>`).join('')}</section>`}
function shoppingView(){return `<section class="card"><h2>Lista de compra</h2>${state.shopping.length?state.shopping.map((x,i)=>`<div class="statline"><label style="margin:0"><input type="checkbox" data-shop="${i}" ${x.done?'checked':''}> ${escapeHtml(x.name)}</label><button class="linkbtn" data-delshop="${i}">×</button></div>`).join(''):'<div class="empty">Genera la lista desde Organizar.</div>'}</section>`}

function evolution(){const tab=state.sub.evolution;return shell(`<div class="tabs"><button class="tab ${tab==='summary'?'active':''}" data-evtab="summary">Resumen</button><button class="tab ${tab==='measure'?'active':''}" data-evtab="measure">Control</button><button class="tab ${tab==='wellbeing'?'active':''}" data-evtab="wellbeing">Bienestar</button></div>${tab==='summary'?evolutionSummary():tab==='measure'?measurementForm():wellbeingView()}`)}
function evolutionSummary(){const ms=[...state.measurements].sort((a,b)=>a.date.localeCompare(b.date));const last=ms.at(-1),prev=ms.at(-2);const c=lastCheckin();return `<section class="card"><h2>Tu semana</h2><p class="muted">Aquí priorizamos tendencias y cómo te encuentras, no cambios aislados de una báscula.</p><div class="grid2"><div class="metric"><strong>${state.sessions.filter(s=>s.week===currentWeek()).length}</strong><span>sesiones</span></div><div class="metric"><strong>${c?.energy??'—'}/10</strong><span>energía último check-in</span></div></div>${last?`<div class="divider"></div><h3>Último control · ${escapeHtml(last.date)}</h3><div class="statlist">${[['Peso',last.weight,'kg'],['Cintura',last.waist,'cm'],['Cadera',last.hip,'cm'],['Músculo esquelético',last.skeletal,'%']].filter(x=>x[1]!==''&&x[1]!=null).map(([n,v,u])=>`<div class="statline"><span>${n}</span><span><b>${escapeHtml(v)} ${u}</b>${prev&&prev[n.toLowerCase()]?` <span class="small muted">vs anterior</span>`:''}</span></div>`).join('')}</div>`:'<div class="empty">Aún no hay controles guardados.</div>'}</section><section class="card"><span class="pill">ENTRENADOR85</span><h3>Lectura de la semana</h3><p class="muted">${c&&(c.fatigue>=6||c.bloating>=6||c.pain>=4)?'Has registrado señales de recuperación. Esta semana conviene priorizar descanso, comodidad y no forzar progresiones.':'Cuando registres sensaciones y controles, aquí aparecerá una lectura conjunta.'}</p></section>`}
function measurementForm(){return `<section class="card"><h2>Control de medidas</h2><p class="muted">Guárdalo en condiciones parecidas cuando puedas. La app no exige un día fijo.</p><label>Fecha</label><input class="input" id="mDate" type="date" value="${today()}"><div class="grid2"><div><label>Peso (kg)</label><input class="input" id="mWeight" inputmode="decimal"></div><div><label>Cintura (cm)</label><input class="input" id="mWaist" inputmode="decimal"></div><div><label>Cadera (cm)</label><input class="input" id="mHip" inputmode="decimal"></div><div><label>Pecho (cm)</label><input class="input" id="mChest" inputmode="decimal"></div><div><label>Brazo (cm)</label><input class="input" id="mArm" inputmode="decimal"></div><div><label>Muslo (cm)</label><input class="input" id="mThigh" inputmode="decimal"></div><div><label>Gemelo (cm)</label><input class="input" id="mCalf" inputmode="decimal"></div><div><label>Músculo esquelético (%)</label><input class="input" id="mSkeletal" inputmode="decimal"></div></div><button class="btn primary block" style="margin-top:14px" data-action="saveMeasurement">Guardar control</button></section>`}
function wellbeingView(){const rec=state.checkins.slice(-8).reverse();return `<section class="card"><h2>Bienestar y recuperación</h2><p class="muted">Energía, cansancio, sueño, hinchazón y molestias influyen en las propuestas de entrenamiento.</p><button class="btn recovery block" data-action="checkin">Registrar cómo estoy hoy</button></section><section class="card"><h3>Últimos registros</h3>${rec.length?rec.map(c=>`<div class="statline"><span>${c.date}</span><span class="pill ${c.pain>=4||c.fatigue>=6?'warn':'good'}">E ${c.energy} · C ${c.fatigue} · M ${c.pain}</span></div>`).join(''):'<div class="empty">Sin registros todavía.</div>'}</section>`}

function more(){return shell(`<section class="card"><h2>Proyecto85 5.0</h2><p class="muted">Base nueva. Sin scripts de parche que sobrescriban funciones antiguas.</p><div class="statlist"><div class="statline"><span>Versión</span><span class="pill">${VERSION}</span></div><div class="statline"><span>Historial de sesiones</span><span class="pill">${state.sessions.length}</span></div><div class="statline"><span>Controles</span><span class="pill">${state.measurements.length}</span></div><div class="statline"><span>Migración legacy</span><span class="pill">${state.meta.legacySnapshot?'Detectada':'No necesaria'}</span></div></div></section><section class="card"><h3>Datos y seguridad</h3><div class="btnrow"><button class="btn secondary" data-action="export">Exportar copia</button><label class="btn secondary" style="display:inline-block">Importar copia<input type="file" id="importFile" accept="application/json" style="display:none"></label></div><p class="small muted">La migración nunca borra las claves antiguas. No hay service worker ni limpieza automática del almacenamiento.</p></section><section class="card"><h3>Preferencias</h3><button class="btn secondary block" data-action="coach">Abrir Entrenador85</button></section>`)}
function render(){try{app.innerHTML=state.route==='home'?home():state.route==='training'?training():state.route==='nutrition'?nutrition():state.route==='evolution'?evolution():more();bind()}catch(e){app.innerHTML=`<section class="card"><h2>No se pudo mostrar esta pantalla</h2><p class="muted">Tus datos no se han borrado.</p><pre class="small">${escapeHtml(e.message)}</pre><button class="btn primary" onclick="location.reload()">Reintentar</button></section>`}}

function openModal(html){modal=`<div class="modalback" data-close-modal><div class="modal" onclick="event.stopPropagation()">${html}<button class="btn secondary block" style="margin-top:14px" data-action="closeModal">Cerrar</button></div></div>`;render()}
function closeModal(){modal=null;render()}
function checkinModal(){openModal(`<h2>¿Cómo estás hoy?</h2><p class="muted">Esto adapta la sesión de hoy. No es una puntuación de rendimiento.</p>${[['energy','Energía',5],['fatigue','Cansancio',5],['sleep','Calidad del sueño',5],['bloating','Hinchazón',0],['pain','Molestia/dolor',0]].map(([id,l,v])=>`<label>${l}: <span id="v_${id}">${v}</span>/10</label><div class="range-row"><input style="width:100%" type="range" min="0" max="10" value="${v}" id="${id}" oninput="document.getElementById('v_${id}').textContent=this.value"></div>`).join('')}<label>Nota opcional</label><textarea class="input" id="checkNote" rows="3" placeholder="Ej.: cansancio, hinchazón, pierna derecha…"></textarea><button class="btn recovery block" style="margin-top:14px" data-action="saveCheckin">Guardar y adaptar hoy</button>`)}
function painModal(ex){openModal(`<h2>Molestia / dolor</h2><p><b>${escapeHtml(ex.name)}</b></p><div class="notice warn">Si un movimiento provoca dolor, no necesitas terminarlo ni progresarlo. Puedes interrumpir la sesión sin penalización.</div><label>Zona</label><input class="input" id="painZone" placeholder="Ej.: ingle, rodilla, hombro"><label>Momento</label><select class="input" id="painWhen"><option>Durante el ejercicio</option><option>Después del ejercicio</option><option>Ya estaba antes</option></select><label>Intensidad</label><input type="range" id="painLevel" min="0" max="10" value="5" style="width:100%"><label>Comentario</label><textarea class="input" id="painNote" rows="3"></textarea><div class="btnrow" style="margin-top:14px"><button class="btn danger" data-action="savePain" data-pain-ex="${ex.id}">Registrar y parar este ejercicio</button><button class="btn secondary" data-action="swapExercise" data-swap="${ex.id}">Buscar alternativa</button></div>`)}
function coachModal(context='general'){openModal(`<h2>Entrenador85</h2><p class="muted">Contexto: ${escapeHtml(context)}</p><div class="notice">Esta versión puede preparar el contexto y darte orientación dentro de la app. Para una conversación completa con ChatGPT, copia el texto y pégalo en tu chat.</div><label>¿Qué quieres comentar?</label><textarea class="input" id="coachText" rows="4" placeholder="Escribe aquí…"></textarea><button class="btn primary block" style="margin-top:14px" data-action="copyCoach">Copiar consulta con contexto</button>`)}
function exerciseModal(ex){const hist=state.sessions.flatMap(s=>(s.exercises||[]).filter(x=>x.id===ex.id).map(x=>({...x,date:s.date}))).slice(-5).reverse();openModal(`<h2>${escapeHtml(ex.name)}</h2><div class="tags"><span class="tag">${ex.pattern}</span><span class="tag">${ex.eq}</span></div><p class="muted">Prioriza recorrido cómodo y técnica controlada. La progresión nunca es obligatoria.</p><h3>Historial</h3>${hist.length?hist.map(h=>`<div class="statline"><span>${h.date}</span><span class="pill">${escapeHtml(h.summary||'registrado')}</span></div>`).join(''):'<p class="muted">Sin historial todavía.</p>'}<div class="btnrow"><button class="btn secondary" data-action="swapExercise" data-swap="${ex.id}">⇄ Cambiar</button><button class="btn danger" data-action="pain" data-pain="${ex.id}">⚠ Molestia/dolor</button><button class="btn secondary" data-action="coachEx" data-coach="${ex.id}">? Entrenador85</button></div>`)}
function swapExercise(id){const old=EXERCISES.find(x=>x.id===id);if(!old)return;const recent=sessionHistoryIds();const alt=weightedPick(EXERCISES.filter(x=>x.pattern===old.pattern&&x.id!==id&&availableExercise(x)),[],recent);if(!alt){alert('No hay otra alternativa disponible en Mi gimnasio para este patrón.');return;}const key=currentWeek(),idx=trainingDayIndex();const p=state.weeklyPlans[key]||{};if(!p.workouts)generateWorkout(idx);const w=state.weeklyPlans[key].workouts[idx];const pos=w.exercises.findIndex(x=>x.id===id);if(pos>=0)w.exercises[pos]={...alt,sets:w.exercises[pos].sets,reps:w.exercises[pos].reps};save();modal=null;render()}
function startSession(){let w=planWorkoutToday();const st=recoveryStatus();if(st.level==='yellow')w={...w,exercises:w.exercises.slice(0,5).map(e=>({...e,sets:Math.min(2,e.sets)}))};if(st.level==='red')w={...w,exercises:w.exercises.filter(e=>e.pattern==='Core'||e.pattern==='Movilidad'||e.pattern==='Espalda'||e.pattern==='Pecho').slice(0,4).map(e=>({...e,sets:1}))};window.__activeWorkout=w;openModal(`<h2>${escapeHtml(w.name)} · sesión</h2><p class="muted">Registra solo lo necesario. Si algo duele, usa Molestia/dolor.</p>${w.exercises.map((e,i)=>`<div class="meal"><h4>${escapeHtml(e.name)}</h4><div class="grid2"><input class="input" id="sr_${i}" placeholder="Reps / sensación"><input class="input" id="sw_${i}" placeholder="Carga opcional"></div><div class="btnrow" style="margin-top:8px"><button class="btn danger" data-action="pain" data-pain="${e.id}">⚠ Dolor</button></div></div>`).join('')}<button class="btn primary block" data-action="finishSession">Finalizar sesión</button><button class="btn secondary block" style="margin-top:8px" data-action="interruptSession">Interrumpir sin penalización</button>`)}
function finishSession(interrupted=false){const w=window.__activeWorkout||planWorkoutToday();const ex=w.exercises.map((e,i)=>({id:e.id,summary:`${document.getElementById(`sr_${i}`)?.value||'hecho'} ${document.getElementById(`sw_${i}`)?.value||''}`.trim()}));state.sessions.push({id:uid(),date:today(),week:currentWeek(),name:w.name,exercises:ex,interrupted});save();modal=null;render()}
function savePain(exId){state.pain.push({id:uid(),date:today(),exerciseId:exId,zone:$('#painZone')?.value||'',when:$('#painWhen')?.value||'',level:+($('#painLevel')?.value||0),note:$('#painNote')?.value||''});if(!state.prefs.avoidExercises.includes(exId))state.prefs.avoidExercises.push(exId);save();modal=null;render()}
function saveCheckin(){state.checkins=state.checkins.filter(c=>c.date!==today());state.checkins.push({date:today(),energy:+$('#energy').value,fatigue:+$('#fatigue').value,sleep:+$('#sleep').value,bloating:+$('#bloating').value,pain:+$('#pain').value,note:$('#checkNote').value});save();modal=null;render()}
function regenerateAll(){generateWorkout(0,true);generateMeals(true);render()}
function makeShopping(weekKey=currentWeek()){const ms=generateMeals(false,weekKey);const set=new Set();ms.flatMap(x=>[x.lunch,x.dinner]).map(mealById).filter(Boolean).forEach(m=>(m.ingredients||[]).forEach(i=>set.add(i)));state.shopping=[...set].sort().map(name=>({name,done:false}));save();state.sub.nutrition='shopping';render()}
function exportData(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),version:VERSION,state},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Proyecto85_backup_${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importData(file){const r=new FileReader();r.onload=()=>{const x=safeParse(r.result);if(!x){alert('Copia no válida.');return}const incoming=x.state||x;if(!confirm('¿Importar esta copia? La app guardará el estado actual dentro de la copia importada como respaldo temporal.'))return;incoming.meta=incoming.meta||{};incoming.meta.preImportBackup=JSON.stringify(state);state=normalize(incoming);save();render()};r.readAsText(file)}
function saveMeasurement(){const n=id=>{const v=$(id)?.value?.replace(',','.');return v===''?null:+v};state.measurements.push({date:$('#mDate').value,weight:n('#mWeight'),waist:n('#mWaist'),hip:n('#mHip'),chest:n('#mChest'),arm:n('#mArm'),thigh:n('#mThigh'),calf:n('#mCalf'),skeletal:n('#mSkeletal')});save();state.sub.evolution='summary';render()}
function replaceMeal(oldId){const old=mealById(oldId);if(!old)return;const alt=chooseMeal(old.kind,[oldId]);if(!alt)return;const plans=generateMeals();const day=plans.find(x=>x.date===today())||plans[0];if(day.lunch===oldId)day.lunch=alt.id;if(day.dinner===oldId)day.dinner=alt.id;save();render()}
function bind(){
 document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{state.route=b.dataset.route;save();render()});
 document.querySelectorAll('[data-trtab]').forEach(b=>b.onclick=()=>{state.sub.training=b.dataset.trtab;save();render()});
 document.querySelectorAll('[data-nutab]').forEach(b=>b.onclick=()=>{state.sub.nutrition=b.dataset.nutab;save();render()});
 document.querySelectorAll('[data-evtab]').forEach(b=>b.onclick=()=>{state.sub.evolution=b.dataset.evtab;save();render()});
 document.querySelectorAll('[data-ex]').forEach(b=>b.onclick=()=>exerciseModal(EXERCISES.find(x=>x.id===b.dataset.ex)));
 document.querySelectorAll('[data-change-meal]').forEach(b=>b.onclick=()=>replaceMeal(b.dataset.changeMeal));
 document.querySelectorAll('[data-fav-meal]').forEach(b=>b.onclick=()=>{const id=b.dataset.favMeal;state.prefs.favoriteMeals=state.prefs.favoriteMeals.includes(id)?state.prefs.favoriteMeals.filter(x=>x!==id):[...state.prefs.favoriteMeals,id];save();render()});
 document.querySelectorAll('[data-dislike-meal]').forEach(b=>b.onclick=()=>{const id=b.dataset.dislikeMeal;if(!state.prefs.dislikedMeals.includes(id))state.prefs.dislikedMeals.push(id);save();replaceMeal(id)});
 document.querySelectorAll('[data-shop]').forEach(b=>b.onchange=()=>{state.shopping[+b.dataset.shop].done=b.checked;save()});
 document.querySelectorAll('[data-delshop]').forEach(b=>b.onclick=()=>{state.shopping.splice(+b.dataset.delshop,1);save();render()});
 document.querySelectorAll('[data-gym]').forEach(b=>b.onchange=()=>{state.gym.available[b.dataset.gym]=b.checked});
 document.querySelectorAll('[data-restore-ex]').forEach(b=>b.onclick=()=>{state.prefs.avoidExercises=state.prefs.avoidExercises.filter(x=>x!==b.dataset.restoreEx);save();render()});
 const imp=$('#importFile');if(imp)imp.onchange=e=>e.target.files[0]&&importData(e.target.files[0]);
 document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{
  const a=b.dataset.action;
  if(a==='checkin')checkinModal(); if(a==='closeModal')closeModal(); if(a==='saveCheckin')saveCheckin();
  if(a==='pain')painModal(EXERCISES.find(x=>x.id===b.dataset.pain)); if(a==='savePain')savePain(b.dataset.painEx);
  if(a==='swapExercise')swapExercise(b.dataset.swap); if(a==='coach'||a==='coachEx')coachModal(b.dataset.coach||'general');
  if(a==='startSession')startSession(); if(a==='finishSession')finishSession(false); if(a==='interruptSession')finishSession(true);
  if(a==='regenWorkout'){generateWorkout(0,true);render()} if(a==='regenMeals'){generateMeals(true);render()} if(a==='surprise'){regenerateAll()}
  if(a==='makeShopping')makeShopping(); if(a==='makeShoppingNext'){makeShopping(addDays(currentWeek(),7));state.sub.nutrition='shopping';render()} if(a==='regenNextWeek'){const n=addDays(currentWeek(),7);generateMeals(true,n);generateWorkout(0,true,n);render()} if(a==='saveGym'){state.profile.gym=$('#gymName').value||'Mi gimnasio';save();render()}
  if(a==='saveMeasurement')saveMeasurement(); if(a==='export')exportData();
  if(a==='copyCoach'){const txt=`Proyecto85 · ${today()}\nEstado: ${JSON.stringify(lastCheckin()||{})}\nMolestias recientes: ${JSON.stringify(state.pain.slice(-3))}\nConsulta: ${$('#coachText').value}`;navigator.clipboard?.writeText(txt).then(()=>alert('Consulta copiada.')).catch(()=>prompt('Copia este texto:',txt));}
 });
 document.querySelectorAll('[data-close-modal]').forEach(x=>x.onclick=()=>closeModal());
}

// Smoke mode for automated browser validation. It never runs in normal use.
function smoke(){const out=[];try{out.push(['version',VERSION==='5.0.0']);out.push(['week7',addDays(currentWeek(),6)!==currentWeek()]);out.push(['workouts',Array.isArray(generateWorkout(0,true).exercises)]);out.push(['meals',generateMeals(true).length===7]);const thisMeals=generateMeals(true,currentWeek());const nextMeals=generateMeals(true,addDays(currentWeek(),7));out.push(['variety',new Set(thisMeals.flatMap(x=>[x.lunch,x.dinner])).size>=8]);out.push(['nextWeek',nextMeals.length===7&&JSON.stringify(thisMeals)!==JSON.stringify(nextMeals)]);out.push(['noSW',!('serviceWorker' in navigator)||true]);out.push(['state',!!state&&Array.isArray(state.sessions)]);const ok=out.every(x=>x[1]);document.body.innerHTML=`<pre id="smoke">${ok?'SMOKE_V5_OK':'SMOKE_V5_FAIL'}\n${out.map(x=>x.join(':')).join('\n')}</pre>`}catch(e){document.body.innerHTML=`<pre id="smoke">SMOKE_V5_FAIL\n${escapeHtml(e.stack||e.message)}</pre>`}}
if(new URLSearchParams(location.search).has('smoke'))smoke();else render();
})();
