(()=>{
"use strict";
const VERSION='6.2.0', KEY='p85coach6_state';
const D=window.P85_DATA, E=window.P85_ENGINE;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uid=()=>crypto?.randomUUID?.()||('id_'+Date.now()+'_'+Math.random().toString(36).slice(2));
const today=()=>E.localISO(new Date());
const safeParse=(s,f=null)=>{try{return JSON.parse(s)}catch{return f}};
const recipeBy=(id,state)=>E.allRecipes(state).find(r=>r.id===id);

function emptyState(){return {version:VERSION,createdAt:new Date().toISOString(),route:'home',sub:{training:'today',nutrition:'today',evolution:'summary'},profile:{name:'',gym:'Basic-Fit Dos Hermanas',theme:'light'},gym:{available:Object.fromEntries(D.EXERCISES.map(x=>[x.equipment,true]))},sessions:[],measurements:[],checkins:[],pain:[],activeSession:null,trainingPlans:{},nutritionPlans:{},legacyPlans:[],mealRatings:{},mealDone:{},customMeals:[],shopping:[],pantry:[],prefs:{dislikedMeals:[],favoriteMeals:[],avoidUntil:{}},meta:{migratedFrom:null,sourceSnapshot:null}}}
function normalize(s){const d=emptyState(),o={...d,...s};o.profile={...d.profile,...(s.profile||{})};o.gym={...d.gym,...(s.gym||{})};o.sub={...d.sub,...(s.sub||{})};o.prefs={...d.prefs,...(s.prefs||{})};o.meta={...d.meta,...(s.meta||{})};['sessions','measurements','checkins','pain','legacyPlans','customMeals','shopping','pantry'].forEach(k=>{if(!Array.isArray(o[k]))o[k]=[]});['trainingPlans','nutritionPlans','mealRatings','mealDone'].forEach(k=>{if(!o[k]||typeof o[k]!=='object')o[k]={}});return o}
function migrate(){const current=safeParse(localStorage.getItem(KEY));if(current)return normalize(current);const out=emptyState();let source=null;
 const v5=safeParse(localStorage.getItem('p85v5_state')); if(v5){source='p85v5_state';Object.assign(out,{sessions:v5.sessions||[],measurements:v5.measurements||[],checkins:v5.checkins||[],pain:v5.pain||[],customMeals:v5.customMeals||[],shopping:v5.shopping||[],pantry:v5.pantry||[]});out.profile={...out.profile,...(v5.profile||{})};out.prefs={...out.prefs,...(v5.prefs||{})};out.meta.sourceSnapshot=JSON.stringify(v5).slice(0,150000);for(const [wk,p] of Object.entries(v5.weeklyPlans||{})){if(p?.meals){out.legacyPlans.push({weekStart:wk,weekEnd:E.add(wk,6),status:'v5',days:Object.fromEntries((p.meals||[]).map((x,i)=>[D.DAYS[i],{lunch:x.lunch,dinner:x.dinner}]))})}}const raw=v5.meta?.legacySnapshot?.raw;const old=safeParse(raw);if(old){out.legacyPlans=[...(old.plans||[]),...out.legacyPlans];out.mealRatings={...(old.ratings||{})};out.mealDone={...(old.mealDone||{})};if(!out.sessions.length&&Array.isArray(old.trainingSessions))out.sessions=old.trainingSessions;if(!out.measurements.length&&Array.isArray(old.measurements))out.measurements=old.measurements}}
 const old=safeParse(localStorage.getItem('p85pro2_state')); if(old){source=source||'p85pro2_state';out.legacyPlans=[...(old.plans||[]),...out.legacyPlans];out.mealRatings={...(old.ratings||{}),...out.mealRatings};out.mealDone={...(old.mealDone||{}),...out.mealDone};if(!out.sessions.length&&Array.isArray(old.trainingSessions))out.sessions=old.trainingSessions;if(!out.measurements.length&&Array.isArray(old.measurements))out.measurements=old.measurements;if(!out.shopping.length&&Array.isArray(old.shopping))out.shopping=old.shopping;if(!out.pantry.length&&Array.isArray(old.pantry))out.pantry=old.pantry}
 out.meta.migratedFrom=source;saveState(out);return normalize(out)}
function saveState(s=state){s.version=VERSION;localStorage.setItem(KEY,JSON.stringify(s))}
let state=migrate();window.P85_STATE=()=>state;

function dayIndex(){const d=new Date(),n=d.getDay();return n>=1&&n<=5?n-1:0}
function currentWeek(){return E.monday(today())}
function currentTraining(){const w=currentWeek(),had=!!state.trainingPlans[w],p=E.buildTrainingWeek(state,w,false);if(!had)saveState();return p}
function currentNutrition(){const w=currentWeek(),had=!!state.nutritionPlans[w],p=E.buildNutritionWeek(state,w,false);if(!had)saveState();return p}
function lastCheckin(){return [...state.checkins].sort((a,b)=>b.date.localeCompare(a.date))[0]||null}
function recovery(){return E.recovery(state)}
function completedThisWeek(){const w=currentWeek();return state.sessions.filter(s=>s.date>=w&&s.date<=E.add(w,6)&&!s.interrupted).length}
function painRecent(){return state.pain.filter(p=>p.date>=E.add(today(),-14)).length}
function nav(){return `<nav class="bottom-nav">${[['home','☀️','Hoy'],['training','🏋️','Entreno'],['nutrition','🍽️','Nutrición'],['evolution','↗','Evolución'],['more','•••','Más']].map(([r,i,l])=>`<button class="nav-btn ${state.route===r?'active':''}" data-route="${r}"><span>${i}</span>${l}</button>`).join('')}</nav>`}
function header(title,sub=''){return `<header class="topbar"><div><div class="eyebrow">ENTRENADOR85 · ${VERSION}</div><h1>${esc(title)}</h1>${sub?`<p>${esc(sub)}</p>`:''}</div><button class="avatar" data-action="coach">85</button></header>`}
function card(title,body,cls=''){return `<section class="card ${cls}"><h3>${title}</h3>${body}</section>`}
function tabs(items,active,attr){return `<div class="tabs">${items.map(([k,l])=>`<button class="tab ${active===k?'active':''}" data-${attr}="${k}">${l}</button>`).join('')}</div>`}

function home(){const rec=recovery(),tr=currentTraining().days[dayIndex()],nut=currentNutrition(),meal=nut.days.find(d=>d.date===today())||nut.days[0];const coach=rec.level==='unknown'?'Haz el check-in de hoy. Con eso adapto el entrenamiento y el tono de la semana.':rec.message;return `${header('Proyecto85 Coach','Tu entrenador personal, no una tabla fija')}
${card(`<span class="status-dot ${rec.level}"></span>${rec.label}`,`<p class="lead">${esc(coach)}</p><div class="btnrow"><button class="btn primary" data-action="checkin">Cómo estoy hoy</button><button class="btn ghost" data-action="coach">Hablar con Entrenador85</button></div>`,'coach-card')}
${card('Entrenamiento de hoy',`<div class="split"><div><div class="big">${esc(tr.name)}</div><p>${tr.exercises.length} ejercicios · cuerpo entero · ${tr.cardio.minutes} min cardio</p></div><button class="btn primary" data-action="startSession">Empezar</button></div><p class="mini">Esta semana: ${completedThisWeek()} sesiones terminadas · ${painRecent()} molestias registradas recientemente.</p>`,'training-accent')}
${card('Comidas de hoy',`<div class="meal-mini">${['breakfast','midmorning','lunch','snack','dinner'].map(t=>`<div><span>${D.MEAL_LABELS[t]}</span><b>${esc(recipeBy(meal[t],state)?.name||'Pendiente')}</b></div>`).join('')}</div><button class="btn ghost" data-route="nutrition">Ver el día completo</button>`,'food-accent')}
${card('Esta semana',`<div class="stats3"><div><b>${completedThisWeek()}</b><span>sesiones</span></div><div><b>${new Set(currentNutrition().days.flatMap(d=>['lunch','dinner'].map(t=>d[t]))).size}</b><span>platos principales</span></div><div><b>${state.measurements.length}</b><span>controles</span></div></div><p class="mini">La variedad se calcula con tu historial; no cambia todo por cambiar.</p>`)}
${nav()}`}

function exerciseLine(ex,i){const ref=E.reference(state,ex);const weight=ref.weight==null?'Sin referencia':`${ref.weight} kg`;return `<div class="exercise-row" data-ex="${ex.id}"><div class="exercise-icon">${i+1}</div><div class="grow"><b>${esc(ex.name)}</b><span>${esc(ex.pattern)} · ${esc(ex.equipment)}</span><small>Sugerencia de hoy: ${weight} · ${esc(ex.reps)}${ref.date?` · basada en ${ref.date}`:''}</small></div><button class="mini-btn" data-action="swap" data-exid="${ex.id}">Cambiar</button></div>`}
function training(){const sub=state.sub.training;return `${header('Entrenamiento','Full Body 5 días · historial, rotación y adaptación diaria')}${tabs([['today','Hoy'],['week','5 días'],['history','Historial'],['gym','Mi gimnasio']],sub,'trtab')}${sub==='today'?trainingToday():sub==='week'?trainingWeek():sub==='history'?trainingHistory():trainingGym()}${nav()}`}
function trainingToday(){const p=currentTraining(),d=p.days[dayIndex()],rec=recovery();return `${card(`${d.name} · ${d.focus}`,`<div class="notice ${rec.level}">${esc(rec.message)}</div>${d.exercises.map(exerciseLine).join('')}<div class="cardio-box"><b>Cardio</b><span>${esc(d.cardio.mode)} · ${d.cardio.minutes} min</span></div><div class="btnrow"><button class="btn primary" data-action="startSession">Empezar sesión</button><button class="btn ghost" data-action="regenTraining">Nueva rotación semanal</button></div>`,'training-accent')}`}
function trainingWeek(){const p=currentTraining();return p.days.map((d,i)=>card(`${D.DAYS[i]} · ${d.name}`,`<p class="mini">Énfasis: ${d.focus}. Sigue siendo cuerpo entero.</p>${d.exercises.map((x,j)=>`<div class="compact"><span>${j+1}. ${esc(x.name)}</span><b>${esc(x.pattern)}</b></div>`).join('')}<div class="compact"><span>${d.cardio.mode}</span><b>${d.cardio.minutes} min</b></div>`)).join('')}
function trainingHistory(){const rows=[...state.sessions].sort((a,b)=>b.date.localeCompare(a.date));return card('Historial real',rows.length?rows.slice(0,30).map(s=>`<div class="history-row"><div><b>${s.date} · ${esc(s.name||s.title||'Sesión')}</b><span>${s.interrupted?'Interrumpida sin penalización':`${(s.exercises||[]).length} ejercicios`}</span></div><span class="pill">${s.interrupted?'Molestia':'✓'}</span></div>`).join(''):'<p>Aún no hay sesiones guardadas.</p>')}
function trainingGym(){const groups={};D.EXERCISES.forEach(x=>(groups[x.equipment]??=[]).push(x));return `${card('Mi gimnasio',`<input id="gymName" class="input" value="${esc(state.profile.gym)}" placeholder="Nombre del gimnasio"><p class="mini">Marca solo el equipamiento que tienes. El generador no propondrá lo desactivado.</p><div class="gym-grid">${Object.keys(groups).sort().map(eq=>`<label class="toggle"><input type="checkbox" data-gym="${esc(eq)}" ${state.gym.available[eq]!==false?'checked':''}><span>${esc(eq)}</span></label>`).join('')}</div><button class="btn primary" data-action="saveGym">Guardar gimnasio</button>`)}`}

function nutrition(){const sub=state.sub.nutrition;return `${header('Nutrición','Cinco momentos del día, biblioteca y decisiones de semana completa')}${tabs([['today','Hoy'],['week','Semana'],['library','Biblioteca'],['prep','Preparación'],['shopping','Compra'],['pantry','Despensa']],sub,'nutab')}${sub==='today'?nutritionToday():sub==='week'?nutritionWeek():sub==='library'?library():sub==='prep'?preparation():sub==='shopping'?shopping():pantry()}${nav()}`}
function mealCard(day,type){const r=recipeBy(day[type],state);if(!r)return '';return `<div class="meal-card"><div><span class="meal-type">${D.MEAL_LABELS[type]}</span><h4>${esc(r.name)}</h4><p>${esc(r.prep||'')} · ${r.time||'?'} min</p></div><div class="meal-actions"><button class="mini-btn" data-action="mealDetail" data-meal="${r.id}">Ver</button><button class="mini-btn" data-action="changeMeal" data-meal="${r.id}" data-date="${day.date}" data-type="${type}">Cambiar con sentido</button></div></div>`}
function nutritionToday(){const p=currentNutrition(),d=p.days.find(x=>x.date===today())||p.days[0];return `${card('Hoy',`<p class="mini">Si cambias una comida, reviso la semana para ofrecer alternativas menos repetidas.</p>${['breakfast','midmorning','lunch','snack','dinner'].map(t=>mealCard(d,t)).join('')}`,'food-accent')}`}
function nutritionWeek(){const p=currentNutrition();return `${card('Plan de la semana',`<div class="btnrow"><button class="btn primary" data-action="regenNutrition">Generar una semana diferente</button><button class="btn ghost" data-action="makeShopping">Actualizar compra</button></div>`)}${p.days.map((d,i)=>card(`${D.DAYS[i]} · ${d.date}`,['breakfast','midmorning','lunch','snack','dinner'].map(t=>`<div class="compact"><span>${D.MEAL_LABELS[t]}</span><b>${esc(recipeBy(d[t],state)?.name||'')}</b></div>`).join(''))).join('')}`}
function library(){const type=state.libraryType||'all',q=(state.libraryQuery||'').toLowerCase();let list=E.allRecipes(state).filter(r=>(type==='all'||r.type===type)&&(!q||r.name.toLowerCase().includes(q)));return card('Biblioteca de comidas',`<div class="grid2"><input id="libSearch" class="input" placeholder="Buscar plato" value="${esc(state.libraryQuery||'')}"><select id="libType" class="input"><option value="all">Todas</option>${Object.entries(D.MEAL_LABELS).map(([k,v])=>`<option value="${k}" ${type===k?'selected':''}>${v}</option>`).join('')}</select></div><button class="btn ghost" data-action="filterLibrary">Filtrar</button><button class="btn primary" data-action="addRecipe">Añadir receta propia</button><div class="library-list">${list.map(r=>`<div class="library-item"><div><b>${esc(r.name)}</b><span>${D.MEAL_LABELS[r.type]||r.type} · ${r.time||'?'} min</span></div><button class="mini-btn" data-action="mealDetail" data-meal="${r.id}">Abrir</button></div>`).join('')}</div>`)}
function preparation(){const p=currentNutrition();const candidates=p.days.flatMap(d=>['lunch','dinner'].map(t=>recipeBy(d[t],state))).filter(Boolean).filter(r=>String(r.prep||'').toLowerCase().includes('prepar')||String(r.prep||'').toLowerCase().includes('batch')||String(r.storage||'').includes('día'));return card('Preparación semanal',`<p class="lead">Deja bases listas, no siete días cocinados de golpe.</p>${candidates.slice(0,8).map(r=>`<div class="prep-item"><b>${esc(r.name)}</b><span>${esc(r.prep||'Preparar con antelación')}</span><small>${esc(r.storage||'')}</small></div>`).join('')}`)}
function makeShopping(){const p=currentNutrition(),m=new Map();for(const d of p.days)for(const t of ['breakfast','midmorning','lunch','snack','dinner']){const r=recipeBy(d[t],state);for(const it of (r?.items||[])){const [name,qty,unit]=it,k=`${name}|${unit}`;m.set(k,{name,qty:(m.get(k)?.qty||0)+(+qty||0),unit,bought:false})}}state.shopping=[...m.values()];saveState()}
function shopping(){if(!state.shopping.length)makeShopping();return card('Lista de compra',`<div class="btnrow"><button class="btn primary" data-action="makeShopping">Recalcular desde la semana</button></div>${state.shopping.map((x,i)=>`<label class="shop-row"><input type="checkbox" data-shop="${i}" ${x.bought?'checked':''}><span>${esc(x.name)}</span><b>${Math.round((+x.qty||0)*10)/10} ${esc(x.unit||'')}</b></label>`).join('')}`)}
function pantry(){return card('Despensa',`<div class="grid2"><input id="pantryName" class="input" placeholder="Producto"><input id="pantryQty" class="input" placeholder="Cantidad"></div><button class="btn primary" data-action="addPantry">Añadir</button>${state.pantry.map((x,i)=>`<div class="history-row"><div><b>${esc(x.name)}</b><span>${esc(x.qty)}</span></div><button class="mini-btn" data-action="delPantry" data-index="${i}">Borrar</button></div>`).join('')}`)}

function evolution(){const sub=state.sub.evolution;return `${header('Evolución','Datos + sensaciones + contexto')}${tabs([['summary','Resumen'],['measure','Control'],['feel','Sensaciones']],sub,'evtab')}${sub==='summary'?evoSummary():sub==='measure'?measureForm():feelForm()}${nav()}`}
function evoSummary(){const ms=[...state.measurements].sort((a,b)=>a.date.localeCompare(b.date)),last=ms.at(-1),prev=ms.at(-2);const delta=(k,u='')=>last&&prev&&last[k]!=null&&prev[k]!=null?`${(last[k]-prev[k]).toFixed(1).replace('.0','')} ${u}`:'—';return `${card('Último control',last?`<div class="stats3"><div><b>${last.weight??'—'}</b><span>peso</span></div><div><b>${last.waist??'—'}</b><span>cintura</span></div><div><b>${last.skeletalMuscle??last.skeletal??'—'}</b><span>músculo esquelético %</span></div></div><p class="mini">Fecha: ${last.date}. Cambio vs control anterior: peso ${delta('weight','kg')}, cintura ${delta('waist','cm')}.</p>`:'<p>Sin controles todavía.</p>')}${card('Lectura del entrenador',`<p class="lead">No interpreto una oscilación aislada de la báscula como un cambio real. Cruzamos medidas, sensaciones y varias semanas.</p><p class="mini">Molestias recientes: ${painRecent()} · Estado de hoy: ${recovery().label}.</p>`)}`}
function measureForm(){const fields=[['weight','Peso (kg)'],['waist','Cintura (cm)'],['hip','Cadera (cm)'],['chest','Pecho (cm)'],['arm','Brazo (cm)'],['thigh','Muslo (cm)'],['calf','Gemelo (cm)'],['bodyFat','Grasa corporal (%)'],['visceral','Grasa visceral'],['water','Agua (%)'],['skeletalMuscle','Músculo esquelético (%)'],['muscleMass','Masa muscular (kg)'],['protein','Proteína (%)'],['bmr','BMR']];return card('Nuevo control',`<label>Fecha<input id="m_date" class="input" type="date" value="${today()}"></label><div class="grid2">${fields.map(([k,l])=>`<label>${l}<input id="m_${k}" class="input" inputmode="decimal"></label>`).join('')}</div><button class="btn primary" data-action="saveMeasure">Guardar control</button>`)}
function feelForm(){const c=lastCheckin();return card('Cómo me encuentro',`<p class="mini">Esto sí modifica el plan del día.</p>${[['energy','Energía',c?.energy||5],['fatigue','Cansancio',c?.fatigue||5],['sleep','Sueño',c?.sleep||5],['bloating','Hinchazón',c?.bloating||0],['pain','Dolor/molestia',c?.pain||0]].map(([id,l,v])=>`<label class="range-row"><span>${l}</span><input id="${id}" type="range" min="0" max="10" value="${v}"><b data-rangeval="${id}">${v}</b></label>`).join('')}<textarea id="checkNote" class="input" placeholder="Algo más que deba saber">${esc(c?.note||'')}</textarea><button class="btn primary" data-action="saveCheckin">Guardar sensaciones</button>`)}

function more(){return `${header('Más','Datos, respaldo y configuración')}${card('Seguridad de tus datos',`<p>Esta versión usa <code>${KEY}</code> y no borra las claves antiguas.</p><div class="btnrow"><button class="btn primary" data-action="export">Exportar copia</button><label class="btn ghost">Importar copia<input id="importFile" type="file" accept="application/json" hidden></label></div><p class="mini">Migración detectada: ${esc(state.meta.migratedFrom||'ninguna')}</p>`)}${card('Entrenador85',`<p class="lead">La app toma decisiones locales con tu historial. Para una conversación abierta, prepara el contexto y lo puedes traer a ChatGPT.</p><button class="btn primary" data-action="coach">Abrir Entrenador85</button>`)}${nav()}`}

function openModal(html){document.body.insertAdjacentHTML('beforeend',`<div class="modal-back"><div class="modal">${html}<button class="modal-x" data-modal-close>×</button></div></div>`);bindModal()}
function closeModal(){document.querySelector('.modal-back')?.remove()}
function checkinModal(){openModal(`<h2>Check-in de hoy</h2>${[['energy','Energía',5],['fatigue','Cansancio',5],['sleep','Sueño',5],['bloating','Hinchazón',0],['pain','Dolor/molestia',0]].map(([id,l,v])=>`<label class="range-row"><span>${l}</span><input id="${id}" type="range" min="0" max="10" value="${v}"><b data-rangeval="${id}">${v}</b></label>`).join('')}<textarea id="checkNote" class="input" placeholder="Comentario"></textarea><button class="btn primary block" data-action="saveCheckin">Guardar y adaptar</button>`)}
function mealDetail(id){const r=recipeBy(id,state);if(!r)return;openModal(`<span class="meal-type">${D.MEAL_LABELS[r.type]||r.type}</span><h2>${esc(r.name)}</h2><p>${esc(r.prep||'')} · ${r.time||'?'} min</p><h3>Ingredientes</h3>${(r.items||[]).map(x=>`<div class="compact"><span>${esc(x[0])}</span><b>${esc(x[1])} ${esc(x[2])}</b></div>`).join('')}<h3>Preparación</h3><ol>${(r.steps||[]).map(s=>`<li>${esc(s)}</li>`).join('')}</ol><p class="mini">Conservación: ${esc(r.storage||'')}</p>`)}
function changeMeal(id,date,type){const alts=E.alternatives(state,id,date,type,currentWeek());openModal(`<h2>Cambiar con sentido</h2><p class="lead">No sustituyo por cualquier cosa. Estas opciones evitan repetir demasiado esta semana.</p>${alts.map(r=>`<button class="alt-choice" data-action="chooseMeal" data-old="${id}" data-new="${r.id}" data-date="${date}" data-type="${type}"><b>${esc(r.name)}</b><span>${esc(r.protein||'')} · ${r.time||'?'} min</span></button>`).join('')}`)}
function coachModal(context='general'){const rec=recovery(),todayPlan=currentTraining().days[dayIndex()];openModal(`<h2>Entrenador85</h2><p class="lead">${esc(rec.message)}</p><p class="mini">Contexto: ${esc(context)} · hoy ${esc(todayPlan.name)} · molestias recientes ${painRecent()}.</p><textarea id="coachText" class="input" rows="4" placeholder="¿Qué necesitas comentar?"></textarea><button class="btn primary block" data-action="copyCoach">Preparar consulta para ChatGPT</button><p class="mini">La app no finge una IA conectada: el análisis local usa reglas e historial. La conversación abierta se hace en ChatGPT.</p>`)}
function painModal(ex){openModal(`<h2>Molestia / dolor</h2><p>${esc(ex?.name||'Ejercicio')}</p><label>Zona<input id="painZone" class="input" placeholder="Ej.: ingle derecha"></label><label>Cuándo aparece<select id="painWhen" class="input"><option>Durante el ejercicio</option><option>Después</option><option>Al caminar/moverme</option></select></label><label>Intensidad<input id="painLevel" type="range" min="0" max="10" value="5"><b data-rangeval="painLevel">5</b></label><textarea id="painNote" class="input" placeholder="Comentario"></textarea><button class="btn primary block" data-action="savePain" data-exid="${ex?.id||''}">Guardar y evitar temporalmente</button><p class="mini">Registrar una molestia nunca cuenta como incumplimiento.</p>`)}
function swapExercise(id){const p=currentTraining(),d=p.days[dayIndex()],pos=d.exercises.findIndex(x=>x.id===id),old=d.exercises[pos];if(pos<0)return;const pool=D.EXERCISES.filter(x=>x.pattern===old.pattern&&x.id!==old.id&&state.gym.available[x.equipment]!==false&&!state.prefs.avoidUntil[x.id]);if(!pool.length)return alert('No hay alternativa disponible de ese grupo en Mi gimnasio.');const chosen=pool[Math.floor(Math.random()*pool.length)];d.exercises[pos]={...chosen,reference:E.reference(state,chosen)};saveState();render()}
function sessionProfile(){
 const rec=recovery();
 if(rec.level==='recovery')return {level:'recovery',label:'Recuperación',mainSets:1,accessorySets:1,cardio:'Opcional y muy cómodo',note:'Hoy priorizamos comodidad. Mantén o reduce la carga si lo necesitas y para cualquier movimiento que moleste.'};
 if(rec.level==='soft')return {level:'soft',label:'Día suave',mainSets:2,accessorySets:1,cardio:'10–15 min cómodo',note:'Mismo cuerpo completo, pero menos volumen. No hace falta progresar hoy.'};
 return {level:'normal',label:'Sesión normal',mainSets:3,accessorySets:2,cardio:null,note:'Uso tu historial como referencia. La carga sugerida es un punto de partida, no una obligación.'};
}
function baseSetCount(ex,prof){const main=['Piernas','Espalda','Pecho'].includes(ex.pattern);return main?prof.mainSets:prof.accessorySets}
function ensureActiveSession(){
 const d=currentTraining().days[dayIndex()],prof=sessionProfile();
 if(state.activeSession&&state.activeSession.date===today()&&state.activeSession.dayIndex===dayIndex())return state.activeSession;
 state.activeSession={id:uid(),date:today(),dayIndex:dayIndex(),week:currentWeek(),name:d.name,startedAt:new Date().toISOString(),recoveryLevel:prof.level,exercises:d.exercises.map(ex=>{const ref=E.reference(state,ex),rep=(String(ref.reps||ex.reps).match(/\d+/)||['10'])[0],count=baseSetCount(ex,prof);return {exerciseId:ex.id,sets:Array.from({length:count},()=>({weight:ref.weight??'',reps:+rep||10,done:false}))}}),cardio:{...d.cardio}};
 saveState();return state.activeSession;
}
function persistActiveInputs(){const a=state.activeSession;if(!a)return; (a.exercises||[]).forEach((e,i)=>(e.sets||[]).forEach((set,j)=>{const w=$(`#w_${i}_${j}`),r=$(`#r_${i}_${j}`),done=$(`#d_${i}_${j}`);if(w)set.weight=w.value;if(r)set.reps=r.value;if(done)set.done=done.checked}));saveState()}
function setRows(exRec,i){return (exRec.sets||[]).map((set,j)=>`<div class="set-line"><span class="set-num">${j+1}</span><input class="input session-input" id="w_${i}_${j}" data-si="${i}" data-sj="${j}" data-field="weight" inputmode="decimal" placeholder="kg" value="${esc(set.weight)}"><input class="input session-input" id="r_${i}_${j}" data-si="${i}" data-sj="${j}" data-field="reps" inputmode="numeric" placeholder="reps" value="${esc(set.reps)}"><label class="done-set"><input type="checkbox" id="d_${i}_${j}" data-si="${i}" data-sj="${j}" data-field="done" ${set.done?'checked':''}>✓</label></div>`).join('')}
function sessionModal(){
 const d=currentTraining().days[dayIndex()],prof=sessionProfile(),a=ensureActiveSession();
 openModal(`<div class="session-head"><div><div class="eyebrow">ENTRENO ACTIVO · ${prof.label}</div><h2>${esc(d.name)}</h2></div><span class="pill">${a.exercises.length} ejercicios</span></div><div class="notice ${prof.level}">${esc(prof.note)}</div>${a.exercises.map((er,i)=>{const ex=D.EXERCISES.find(x=>x.id===er.exerciseId),ref=E.reference(state,ex);return `<div class="session-ex"><div class="session-ex-title"><div><b>${esc(ex.name)}</b><span>${esc(ex.pattern)} · ${esc(ex.equipment)}</span><small>${ref.weight==null?'Sin carga previa':`Última referencia: ${ref.weight} kg · ${esc(ref.reps)}${ref.date?` · ${ref.date}`:''}`}</small></div><button class="mini-btn danger" data-action="pain" data-exid="${ex.id}">⚠ Molestia</button></div><div class="set-grid-v61">${setRows(er,i)}</div><div class="btnrow compact-actions"><button class="mini-btn" data-action="addSet" data-index="${i}" ${er.sets.length>=3?'disabled':''}>+ Serie</button><button class="mini-btn" data-action="removeSet" data-index="${i}" ${er.sets.length<=1?'disabled':''}>− Serie</button></div></div>`}).join('')}<div class="cardio-box"><b>Cardio</b><span>${esc(prof.cardio||`${d.cardio.mode} · ${d.cardio.minutes} min`)}</span></div><div class="btnrow"><button class="btn primary" data-action="finishSession">Finalizar sesión</button><button class="btn ghost" data-action="interruptSession">Interrumpir sin penalización</button></div>`);
 bindSessionInputs();
}
function bindSessionInputs(){$$('.session-input,[data-field="done"]').forEach(el=>{const ev=el.type==='checkbox'?'change':'input';el.addEventListener(ev,()=>{const i=+el.dataset.si,j=+el.dataset.sj,f=el.dataset.field;const a=state.activeSession;if(!a?.exercises?.[i]?.sets?.[j])return;a.exercises[i].sets[j][f]=f==='done'?el.checked:el.value;saveState()})})}
function addSet(i){persistActiveInputs();const e=state.activeSession?.exercises?.[i];if(!e||e.sets.length>=3)return;const last=e.sets[e.sets.length-1]||{weight:'',reps:10,done:false};e.sets.push({weight:last.weight,reps:last.reps,done:false});saveState();closeModal();sessionModal()}
function removeSet(i){persistActiveInputs();const e=state.activeSession?.exercises?.[i];if(!e||e.sets.length<=1)return;e.sets.pop();saveState();closeModal();sessionModal()}
function finishSession(interrupted=false){persistActiveInputs();const a=state.activeSession;if(!a)return;const exs=(a.exercises||[]).map(e=>({exerciseId:e.exerciseId,sets:(e.sets||[]).map(x=>({weight:+String(x.weight||0).replace(',','.'),reps:+x.reps||0,done:!!x.done})),effort:null}));state.sessions.push({id:a.id,date:a.date,dayIndex:a.dayIndex,name:a.name,startedAt:a.startedAt,exercises:exs,cardio:a.cardio,interrupted,finishedAt:new Date().toISOString()});state.activeSession=null;saveState();closeModal();render()}
function savePain(exid){state.pain.push({id:uid(),date:today(),exerciseId:exid,zone:$('#painZone')?.value||'',when:$('#painWhen')?.value||'',level:+($('#painLevel')?.value||0),note:$('#painNote')?.value||''});state.prefs.avoidUntil[exid]=E.add(today(),14);saveState();closeModal();if(state.activeSession)sessionModal();else render()}
function saveCheckin(){state.checkins=state.checkins.filter(x=>x.date!==today());state.checkins.push({date:today(),energy:+$('#energy').value,fatigue:+$('#fatigue').value,sleep:+$('#sleep').value,bloating:+$('#bloating').value,pain:+$('#pain').value,note:$('#checkNote')?.value||''});state.activeSession=null;saveState();closeModal();render()}
function saveMeasure(){const obj={date:$('#m_date').value};['weight','waist','hip','chest','arm','thigh','calf','bodyFat','visceral','water','skeletalMuscle','muscleMass','protein','bmr'].forEach(k=>{const v=$(`#m_${k}`)?.value?.replace(',','.');obj[k]=v===''||v==null?null:+v});state.measurements.push(obj);saveState();state.sub.evolution='summary';render()}
function addRecipeModal(){openModal(`<h2>Receta propia</h2><label>Nombre<input id="cr_name" class="input"></label><label>Momento<select id="cr_type" class="input">${Object.entries(D.MEAL_LABELS).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><label>Ingredientes<textarea id="cr_items" class="input" placeholder="Uno por línea"></textarea></label><label>Preparación<textarea id="cr_steps" class="input"></textarea></label><button class="btn primary block" data-action="saveRecipe">Guardar receta</button>`)}
function saveRecipe(){const name=$('#cr_name').value.trim();if(!name)return;state.customMeals.push({id:'custom_'+uid(),type:$('#cr_type').value,name,time:10,prep:'Receta propia',items:$('#cr_items').value.split('\n').filter(Boolean).map(x=>[x.trim(),'','']),steps:$('#cr_steps').value.split('\n').filter(Boolean)});saveState();closeModal();render()}
function exportData(){const b=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),version:VERSION,state},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`Proyecto85_backup_${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importData(file){const fr=new FileReader();fr.onload=()=>{const j=safeParse(fr.result);if(!j)return alert('Copia no válida');if(!confirm('¿Importar la copia? No se borran las claves antiguas.'))return;state=normalize(j.state||j);saveState();render()};fr.readAsText(file)}
function copyCoach(){const txt=`Proyecto85 · ${today()}\nEstado: ${JSON.stringify(lastCheckin()||{})}\nMolestias recientes: ${JSON.stringify(state.pain.slice(-5))}\nSesiones recientes: ${JSON.stringify(state.sessions.slice(-3))}\nConsulta: ${$('#coachText').value}`;navigator.clipboard?.writeText(txt).then(()=>alert('Contexto copiado. Pégalo en ChatGPT.')).catch(()=>prompt('Copia este texto:',txt))}

function render(){const root=$('#app');root.innerHTML=state.route==='home'?home():state.route==='training'?training():state.route==='nutrition'?nutrition():state.route==='evolution'?evolution():more();bind()}
function bind(){$$('[data-route]').forEach(x=>x.onclick=()=>{state.route=x.dataset.route;saveState();render()});$$('[data-trtab]').forEach(x=>x.onclick=()=>{state.sub.training=x.dataset.trtab;saveState();render()});$$('[data-nutab]').forEach(x=>x.onclick=()=>{state.sub.nutrition=x.dataset.nutab;saveState();render()});$$('[data-evtab]').forEach(x=>x.onclick=()=>{state.sub.evolution=x.dataset.evtab;saveState();render()});$$('[data-ex]').forEach(x=>x.onclick=e=>{if(e.target.closest('button'))return;const ex=D.EXERCISES.find(y=>y.id===x.dataset.ex);openModal(`<h2>${esc(ex.name)}</h2><p>${esc(ex.tech)}</p><p class="mini">${esc(ex.pattern)} · ${esc(ex.equipment)}</p><div class="btnrow"><button class="btn ghost" data-action="swap" data-exid="${ex.id}">Cambiar</button><button class="btn ghost danger" data-action="pain" data-exid="${ex.id}">Molestia</button></div>`)});$$('[data-gym]').forEach(x=>x.onchange=()=>{state.gym.available[x.dataset.gym]=x.checked;saveState()});$$('[data-shop]').forEach(x=>x.onchange=()=>{state.shopping[+x.dataset.shop].bought=x.checked;saveState()});const imp=$('#importFile');if(imp)imp.onchange=e=>e.target.files?.[0]&&importData(e.target.files[0]);$$('[data-rangeval]').forEach(b=>{const i=$(`#${b.dataset.rangeval}`);if(i)i.oninput=()=>b.textContent=i.value});$$('[data-action]').forEach(b=>b.onclick=e=>{e.stopPropagation();const a=b.dataset.action;if(a==='checkin')checkinModal();if(a==='coach')coachModal();if(a==='startSession')sessionModal();if(a==='swap')swapExercise(b.dataset.exid);if(a==='pain')painModal(D.EXERCISES.find(x=>x.id===b.dataset.exid));if(a==='regenTraining'){delete state.trainingPlans[currentWeek()];E.buildTrainingWeek(state,currentWeek(),true);saveState();render()}if(a==='regenNutrition'){delete state.nutritionPlans[currentWeek()];E.buildNutritionWeek(state,currentWeek(),true);saveState();render()}if(a==='mealDetail')mealDetail(b.dataset.meal);if(a==='changeMeal')changeMeal(b.dataset.meal,b.dataset.date,b.dataset.type);if(a==='filterLibrary'){state.libraryQuery=$('#libSearch').value;state.libraryType=$('#libType').value;saveState();render()}if(a==='addRecipe')addRecipeModal();if(a==='makeShopping'){makeShopping();render()}if(a==='addPantry'){const n=$('#pantryName').value.trim(),q=$('#pantryQty').value.trim();if(n)state.pantry.push({name:n,qty:q});saveState();render()}if(a==='delPantry'){state.pantry.splice(+b.dataset.index,1);saveState();render()}if(a==='saveGym'){state.profile.gym=$('#gymName')?.value||state.profile.gym;saveState();render()}if(a==='saveMeasure')saveMeasure();if(a==='saveCheckin')saveCheckin();if(a==='savePain')savePain(b.dataset.exid);if(a==='finishSession')finishSession(false);if(a==='interruptSession')finishSession(true);if(a==='export')exportData();if(a==='copyCoach')copyCoach();if(a==='saveRecipe')saveRecipe();});}
function bindModal(){const back=document.querySelector('.modal-back');if(back)back.onclick=e=>{if(e.target===back)closeModal()};$$('[data-modal-close]').forEach(x=>x.onclick=e=>{e.preventDefault();e.stopPropagation();closeModal()});$$('[data-rangeval]').forEach(b=>{const i=$(`#${b.dataset.rangeval}`);if(i)i.oninput=()=>b.textContent=i.value});$$('[data-action]').forEach(b=>b.onclick=e=>{e.stopPropagation();const a=b.dataset.action;if(a==='saveCheckin')saveCheckin();if(a==='savePain')savePain(b.dataset.exid);if(a==='pain'){persistActiveInputs();painModal(D.EXERCISES.find(x=>x.id===b.dataset.exid))}if(a==='addSet')addSet(+b.dataset.index);if(a==='removeSet')removeSet(+b.dataset.index);if(a==='swap'){closeModal();swapExercise(b.dataset.exid)}if(a==='finishSession')finishSession(false);if(a==='interruptSession')finishSession(true);if(a==='copyCoach')copyCoach();if(a==='saveRecipe')saveRecipe();if(a==='chooseMeal'){const p=currentNutrition(),d=p.days.find(x=>x.date===b.dataset.date);if(d)d[b.dataset.type]=b.dataset.new;saveState();closeModal();render()}})}

function smoke(){const results=[];try{results.push(['version',VERSION==='6.2.0']);results.push(['recipes',D.RECIPES.length>=50]);results.push(['fiveMealTypes',new Set(D.RECIPES.map(r=>r.type)).size===5]);const tp=E.buildTrainingWeek(state,currentWeek(),true);results.push(['fiveFullBodyDays',tp.days.length===5&&tp.days.every(d=>d.exercises.length===9&&['Piernas','Espalda','Pecho','Hombros','Bíceps','Tríceps','Core'].every(g=>d.exercises.some(x=>x.pattern===g)))]);const np=E.buildNutritionWeek(state,currentWeek(),true);results.push(['nutrition7',np.days.length===7&&np.days.every(d=>['breakfast','midmorning','lunch','snack','dinner'].every(t=>!!d[t]))]);results.push(['history',Array.isArray(state.sessions)]);results.push(['measurements',Array.isArray(state.measurements)]);const ok=results.every(x=>x[1]);document.body.innerHTML=`<pre id="smoke">${ok?'SMOKE_V62_OK':'SMOKE_V62_FAIL'}\n${results.map(x=>x.join(':')).join('\n')}</pre>`}catch(e){document.body.innerHTML=`<pre id="smoke">SMOKE_V62_FAIL\n${esc(e.stack||e.message)}</pre>`}}
if(new URLSearchParams(location.search).has('smoke'))smoke();else render();
})();
