const ex=[["Prensa",3,10,50,"52 kg solo si la rodilla está a 0–1/10"],["Curl femoral",3,10,42,"Mantener carga"],["Jalón al pecho",3,10,50,""],["Remo con apoyo",3,10,35,""],["Press de pecho",3,10,36,""],["Peck Deck",3,12,50,""],["Press militar",3,12,13,""],["Elevaciones laterales",3,15,8,""],["Face Pull",3,15,15.9,""],["Curl bíceps",3,12,13.6,""],["Tríceps polea",3,12,15.9,""]];
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],get=k=>JSON.parse(localStorage.getItem(k)||"[]"),set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function go(id){qa(".view").forEach(v=>v.classList.toggle("active",v.id===id));qa("nav button").forEach(b=>b.classList.toggle("active",b.dataset.go===id));if(id==="historial")renderHistory();if(id==="progreso")renderMeasures()}
qa("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));
q("#list").innerHTML=ex.map((e,i)=>`<div class="exercise"><h3>${i+1}. ${e[0]}</h3><div class="target">${e[1]} × ${e[2]} · ${e[3]} kg</div>${e[4]?`<p class="muted">${e[4]}</p>`:""}${Array.from({length:e[1]},(_,j)=>`<div class="set"><b>${j+1}</b><input type="number" step=".1" value="${e[3]}"><input type="number" value="${e[2]}"><input class="check" type="checkbox"></div>`).join("")}</div>`).join("");
q("#pain").oninput=e=>{q("#painTxt").textContent=e.target.value;q("#painAdvice").textContent=+e.target.value<=1?"Entrena con control y no subas carga.":+e.target.value<=3?"Reduce carga de piernas y evita impacto.":"No hagas prensa ni extensiones; detente si aumenta."};
q("#saveSession").onclick=()=>{let a=get("p85s");a.unshift({date:new Date().toLocaleString("es-ES"),duration:q("#duration").value,rpe:q("#rpe").value,cardio:q("#cardio").value,pain:q("#pain").value,notes:q("#notes").value});set("p85s",a);update();alert("Sesión guardada");go("historial")};
q("#saveMeasures").onclick=()=>{let a=get("p85m");a.unshift({date:new Date().toLocaleDateString("es-ES"),weight:q("#weight").value,waist:q("#waist").value,chest:q("#chest").value,hip:q("#hip").value});set("p85m",a);update();renderMeasures();alert("Medidas guardadas")};
function renderHistory(){let a=get("p85s");q("#history").innerHTML=a.length?a.map(x=>`<div class="history"><b>${x.date}</b><p>${x.duration||"-"} min · Sensación ${x.rpe||"-"}/10 · Cardio ${x.cardio||0} min</p><span class="muted">Rodilla ${x.pain}/10 ${x.notes?("· "+x.notes):""}</span></div>`).join(""):`<div class="card muted">Todavía no hay sesiones.</div>`}
function renderMeasures(){let a=get("p85m");q("#measureHistory").innerHTML=a.map(x=>`<div class="history"><b>${x.date}</b><p>${x.weight} kg · Cintura ${x.waist} cm · Pecho ${x.chest} cm</p></div>`).join("")}
function update(){let s=get("p85s"),m=get("p85m");q("#count").textContent=s.length;if(m[0])q("#homeWeight").textContent=String(m[0].weight).replace(".",",")+" kg"}
q("#exportData").onclick=()=>{let blob=new Blob([JSON.stringify({sesiones:get("p85s"),medidas:get("p85m")},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="Proyecto85-copia.json";a.click()};
if("serviceWorker" in navigator)navigator.serviceWorker.register("./sw.js");update();